# 1. Define the database file name (it will be created in your project folder)
spring.datasource.url=jdbc:sqlite:robot-arm.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# SQLite specific: Ensure only one connection to prevent locking issues
spring.datasource.hikari.maximum-pool-size=1

# 2. The Critical Dialect Setting
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 3. Let Hibernate create tables for you automatically
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL in console so you can see what's happening
spring.jpa.show-sql=true

# Robot Movement Configuration
robot.movement.max-speed=200.0
robot.movement.max-speed-frequency=10000
robot.movement.full-circle-steps=200
robot.movement.microstep-factor=8
robot.movement.interpolation-step-millis=50

#Telemetry logging
#logging.level.com.sundtrack.robotarm.serial.service=DEBUG
